# Generated by Django 4.2.4 on 2023-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'waiting approval'), ('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
